### ISSUE TITLE
Question about splitting of Nuscenes

### ISSUE THREAD

**Issue by ChengkaiYang** [vita-epfl/UniTraj#34] opened 2024-10-30 17:22 UTC
Dear @Alan-LanFeng 
        I noticed that in unitraj origin code, 'train_data_path' and 'val_data_path' are all set 'data_samples/nuscenes', which means we use same part of dataset to train and eval.
        Moreover, in your paper, it said nuscenes has 32k trajectories, but when I'm following unitraj's code, it only has 1136 trajectories for 1136 scenes(one trajectory for each scenario).Could you please tell me how to fix these problems?Thanks!

**Comment by Alan-LanFeng** [comment] 2024-10-31 15:02
Duplicate of #9

**Closed** 2024-11-07 13:24 UTC
